# Makefile.deps created Thu Mar 27 16:26:30 PDT 2014
commands.o: commands.cpp commands.h inode.h util.h util.tcc debug.h
debug.o: debug.cpp debug.h util.h util.tcc
inode.o: inode.cpp debug.h inode.h util.h util.tcc
util.o: util.cpp util.h util.tcc debug.h
main.o: main.cpp commands.h inode.h util.h util.tcc debug.h
