# Makefile.dep created Fri Dec 11 17:12:30 PST 2015
bigint.o: bigint.cpp bigint.h debug.h relops.h ubigint.h
ubigint.o: ubigint.cpp ubigint.h debug.h relops.h
libfns.o: libfns.cpp libfns.h bigint.h debug.h relops.h ubigint.h
scanner.o: scanner.cpp scanner.h debug.h
debug.o: debug.cpp debug.h general.h
general.o: general.cpp general.h debug.h
main.o: main.cpp bigint.h debug.h relops.h ubigint.h general.h \
 iterstack.h libfns.h scanner.h
